In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [4]:
#Loading the dataset

df = pd.read_csv("milan_cortina_2026_athletes.csv")
df.head()

,Athlete_ID,Athlete_Name,Country,Gender,Age,Sport,Previous_Olympics,Training_Hours_Per_Week,Altitude_Training_m,Body_Fat_Pct,VO2max,Reaction_Time_ms,Career_Injuries,World_Cup_Points_Preseason,Country_GDP_per_capita,Winter_Sport_Tradition_Index,Medal
0,MC26_1001,Ben Ogden,USA,M,26,Cross-Country,1,35.6,1687.0,NaN,91.5,NaN,1,356.0,80000,0.82,Silver
1,MC26_1002,Loic Meillard,SUI,M,30,Alpine Skiing,3,22.9,2289.0,13.9,71.4,208.0,1,977.0,93000,0.93,Gold
2,MC26_1003,Francesca Lollobrigida,ITA,F,35,Speed Skating,1,29.0,394.0,10.1,82.6,189.0,3,416.0,38000,0.82,Gold
3,MC26_1004,Maria Nilsson,FRA,F,43,Ski Jumping,4,26.2,1239.0,9.1,59.3,183.0,2,801.0,48000,0.87,NaN
4,MC26_1005,Nils Lewis,GER,M,20,Short Track,0,20.2,67.0,12.3,63.1,187.0,2,393.0,52000,0.88,NaN

In [6]:
df.shape

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 17 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Athlete_ID                    390 non-null    object
 1   Athlete_Name                  390 non-null    object
 2   Country                       390 non-null    object
 3   Gender                        390 non-null    object
 4   Age                           390 non-null    int64
 5   Sport                         390 non-null    object
 6   Previous_Olympics             390 non-null    int64
 7   Training_Hours_Per_Week       363 non-null    float64
 8   Altitude_Training_m           366 non-null    float64
 9   Body_Fat_Pct                  359 non-null    float64
 10  VO2max                        362 non-null    float64
 11  Reaction_Time_ms              288 non-null    float64
 12  Career_Injuries               390 non-null    int64
 13  World_Cup_Points_Preseason    292 non-null    float64
 14  Country_GDP_per_capita        390 non-null    int64
 15  Winter_Sport_Tradition_Index  390 non-null    float64
 16  Medal                         104 non-null    object
dtypes: float64(7), int64(4), object(6)
memory usage: 51.9+ KB

In [7]:
# Missing values table
missing_table = pd.DataFrame({
    "Missing_Count": df.isna().sum(),
    "Missing_Percent": (df.isna().mean() * 100).round(2)
}).sort_values("Missing_Percent", ascending=False)

missing_table

                              Missing_Count  Missing_Percent
Medal                                   286            73.33
Reaction_Time_ms                        102            26.15
World_Cup_Points_Preseason               98            25.13
Body_Fat_Pct                             31             7.95
VO2max                                   28             7.18
Training_Hours_Per_Week                  27             6.92
Altitude_Training_m                      24             6.15
Previous_Olympics                         0             0.00
Athlete_Name                              0             0.00
Sport                                     0             0.00
Age                                       0             0.00
Gender                                    0             0.00
Career_Injuries                           0             0.00
Country                                   0             0.00
Country_GDP_per_capita                    0             0.00
Winter_Sport_Tradition_Index              0             0.00
Athlete_ID                                0             0.00

In [8]:
# Basic descriptive statistics
df.describe(include="all")

,Athlete_ID,Athlete_Name,Country,Gender,Age,Sport,Previous_Olympics,Training_Hours_Per_Week,Altitude_Training_m,Body_Fat_Pct,VO2max,Reaction_Time_ms,Career_Injuries,World_Cup_Points_Preseason,Country_GDP_per_capita,Winter_Sport_Tradition_Index,Medal
count,390,390,390,390,390.000000,390,390.000000,363.000000,366.000000,359.000000,362.000000,288.000000,390.00000,292.000000,390.000000,390.000000,104
unique,390,369,23,2,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,MC26_1001,Emily Taylor,CAN,F,NaN,Alpine Skiing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Gold
freq,1,3,48,201,NaN,60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,49
mean,NaN,NaN,NaN,NaN,31.166667,NaN,2.246154,25.985124,1118.756831,12.037047,68.691713,192.836806,2.55641,594.198630,53502.564103,0.773667,NaN
std,NaN,NaN,NaN,NaN,7.145237,NaN,1.434400,9.207407,827.076931,5.355902,12.030303,25.804095,1.86309,300.689565,22241.459320,0.197849,NaN
min,NaN,NaN,NaN,NaN,9.000000,NaN,0.000000,13.000000,1.000000,6.500000,-8.400000,143.000000,0.00000,82.000000,11000.000000,0.040000,NaN
25%,NaN,NaN,NaN,NaN,25.250000,NaN,1.000000,21.700000,182.000000,9.800000,60.925000,174.000000,1.00000,324.750000,38000.000000,0.710000,NaN
50%,NaN,NaN,NaN,NaN,31.000000,NaN,2.000000,25.200000,1344.500000,11.600000,66.750000,191.000000,2.00000,581.500000,55000.000000,0.850000,NaN
75%,NaN,NaN,NaN,NaN,37.000000,NaN,3.000000,29.000000,1835.000000,13.350000,76.875000,210.000000,4.00000,834.500000,62000.000000,0.880000,NaN
max,NaN,NaN,NaN,NaN,47.000000,NaN,5.000000,172.000000,2582.000000,99.200000,96.000000,259.000000,8.00000,1363.000000,95000.000000,0.970000,NaN

In [10]:
#Finding the 4 possible planted errors
#Age Check
df.sort_values("Age")[["Athlete_Name","Country","Sport","Age"]].head(10)

         Athlete_Name Country             Sport  Age
169    Pierre Johnson     GBR        Ice Hockey    9
194     Viktor Muller     KOR     Speed Skating   19
346  Brandon Thompson     CAN  Freestyle Skiing   19
158      Sofia Keller     SWE     Cross-Country   19
177    Dylan Campbell     POL          Biathlon   19
45          Choi Gaon     KOR         Snowboard   19
379     Andrew Harris     NOR  Freestyle Skiing   19
388      Maria Murray     AUS     Alpine Skiing   19
372    Nicolas Thomas     AUS     Speed Skating   19
367      Nina Schmidt     CZE     Speed Skating   19

In [11]:
df.sort_values("Training_Hours_Per_Week", ascending=False)[["Athlete_Name","Sport","Training_Hours_Per_Week"]].head(10)

               Athlete_Name          Sport  Training_Hours_Per_Week
327           Kyle Thompson  Speed Skating                    172.0
11             Kayla Keller       Biathlon                     37.8
288          Frida Karlsson  Cross-Country                     37.7
225  Johannes Høsflot Klæbo  Cross-Country                     36.8
31           Ebba Andersson  Cross-Country                     36.6
190            Nick Bernard  Cross-Country                     36.4
228          Sofia Anderson  Cross-Country                     36.3
341         Mathis Desloges  Cross-Country                     36.2
16           Martin Nyenget  Cross-Country                     36.2
158            Sofia Keller  Cross-Country                     36.1

In [12]:
df.sort_values("VO2max")[["Athlete_Name","Sport","VO2max"]].head(10)

        Athlete_Name        Sport  VO2max
9     Nathan Fischer  Short Track    -8.4
123     Tobias Lewis      Curling    41.7
150      Emma Murray      Curling    42.0
32      Pierre Bauer      Curling    43.2
257    Maja Campbell      Curling    44.4
43       Agnes Lewis      Curling    44.7
215     Tyler Murray      Curling    46.2
224      Maja Miller      Curling    48.3
361  Ingrid Robinson         Luge    49.0
82      Hanna Miller      Curling    50.4

In [13]:
df.sort_values("Body_Fat_Pct", ascending=False)[["Athlete_Name","Sport","Body_Fat_Pct"]].head(10)

      Athlete_Name      Sport  Body_Fat_Pct
175   Jonas Wilson  Snowboard          99.2
142    Brad Gushue    Curling          23.4
43     Agnes Lewis    Curling          22.9
257  Maja Campbell    Curling          22.0
107    Maria Lewis    Curling          21.3
35     Niklas Edin    Curling          21.3
224    Maja Miller    Curling          21.1
82    Hanna Miller    Curling          20.9
326   Anja Steiner    Curling          19.7
215   Tyler Murray    Curling          18.7

In [14]:
import numpy as np

# Create working copy
df_clean = df.copy()

# Replace impossible values with NaN
df_clean.loc[df_clean["Age"] == 9, "Age"] = np.nan
df_clean.loc[df_clean["Training_Hours_Per_Week"] == 172, "Training_Hours_Per_Week"] = np.nan
df_clean.loc[df_clean["VO2max"] == -8.4, "VO2max"] = np.nan
df_clean.loc[df_clean["Body_Fat_Pct"] == 99.2, "Body_Fat_Pct"] = np.nan

In [15]:
df_clean.isna().sum()

Athlete_ID                        0
Athlete_Name                      0
Country                           0
Gender                            0
Age                               1
Sport                             0
Previous_Olympics                 0
Training_Hours_Per_Week          28
Altitude_Training_m              24
Body_Fat_Pct                     32
VO2max                           29
Reaction_Time_ms                102
Career_Injuries                   0
World_Cup_Points_Preseason       98
Country_GDP_per_capita            0
Winter_Sport_Tradition_Index      0
Medal                           286
dtype: int64

In [17]:
#Hidden Duplication detection
duplicates = df_clean[df_clean.duplicated(
    subset=df_clean.columns.difference(["Athlete_ID"]),
    keep=False
)]

duplicates.sort_values("Athlete_Name")

,Athlete_ID,Athlete_Name,Country,Gender,Age,Sport,Previous_Olympics,Training_Hours_Per_Week,Altitude_Training_m,Body_Fat_Pct,VO2max,Reaction_Time_ms,Career_Injuries,World_Cup_Points_Preseason,Country_GDP_per_capita,Winter_Sport_Tradition_Index,Medal
131,MC26_1132,Brandon Bernard,CHN,M,42.0,Ice Hockey,2,22.5,155.0,12.0,61.9,165.0,1,NaN,13000,0.62,NaN
274,MC26_1275,Brandon Bernard,CHN,M,42.0,Ice Hockey,2,22.5,155.0,12.0,61.9,165.0,1,NaN,13000,0.62,NaN
128,MC26_1129,Lisa Martin,JPN,F,24.0,Alpine Skiing,2,26.2,1835.0,9.2,63.8,177.0,3,745.0,35000,0.74,NaN
382,MC26_1383,Lisa Martin,JPN,F,24.0,Alpine Skiing,2,26.2,1835.0,9.2,63.8,177.0,3,745.0,35000,0.74,NaN
275,MC26_1276,Trevor Martin,FRA,M,37.0,Ice Hockey,1,23.2,NaN,14.6,NaN,219.0,5,NaN,48000,0.87,NaN
355,MC26_1356,Trevor Martin,FRA,M,37.0,Ice Hockey,1,23.2,NaN,14.6,NaN,219.0,5,NaN,48000,0.87,NaN

In [18]:
# Remove duplicates while keeping first occurrence
df_clean = df_clean.drop_duplicates(
    subset=df_clean.columns.difference(["Athlete_ID"]),
    keep="first"
)

df_clean.shape

(387, 17)

In [19]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
385    False
386    False
387    False
388    False
389    False
Length: 390, dtype: bool

In [20]:
#Missing medal handling
df_clean["Medal"] = df_clean["Medal"].fillna("None")
df_clean["Medal"].value_counts()

Medal
None      283
Gold       49
Silver     32
Bronze     23
Name: count, dtype: int64

In [21]:
# Check remaining missing values
df_clean.isna().sum()

Athlete_ID                        0
Athlete_Name                      0
Country                           0
Gender                            0
Age                               1
Sport                             0
Previous_Olympics                 0
Training_Hours_Per_Week          28
Altitude_Training_m              23
Body_Fat_Pct                     32
VO2max                           28
Reaction_Time_ms                102
Career_Injuries                   0
World_Cup_Points_Preseason       96
Country_GDP_per_capita            0
Winter_Sport_Tradition_Index      0
Medal                             0
dtype: int64

In [22]:
#Sport-Specific Median Imputation for Missing Performance Variables
# Age by sport
df_clean["Age"] = df_clean["Age"].fillna(
    df_clean.groupby("Sport")["Age"].transform("median")
)

# Training Hours by sport
df_clean["Training_Hours_Per_Week"] = df_clean["Training_Hours_Per_Week"].fillna(
    df_clean.groupby("Sport")["Training_Hours_Per_Week"].transform("median")
)

# Altitude by sport
df_clean["Altitude_Training_m"] = df_clean["Altitude_Training_m"].fillna(
    df_clean.groupby("Sport")["Altitude_Training_m"].transform("median")
)

# VO2max by sport
df_clean["VO2max"] = df_clean["VO2max"].fillna(
    df_clean.groupby("Sport")["VO2max"].transform("median")
)

In [23]:
#Gender-and-Sport Specific Imputation for Body Fat Percentage
df_clean["Body_Fat_Pct"] = df_clean["Body_Fat_Pct"].fillna(
    df_clean.groupby(["Gender","Sport"])["Body_Fat_Pct"].transform("median")
)

In [24]:
df_clean.isna().sum()

Athlete_ID                        0
Athlete_Name                      0
Country                           0
Gender                            0
Age                               0
Sport                             0
Previous_Olympics                 0
Training_Hours_Per_Week           0
Altitude_Training_m               0
Body_Fat_Pct                      0
VO2max                            0
Reaction_Time_ms                102
Career_Injuries                   0
World_Cup_Points_Preseason       96
Country_GDP_per_capita            0
Winter_Sport_Tradition_Index      0
Medal                             0
dtype: int64

In [25]:
#Handling MNAR Variables with Missingness Indicators
# Missingness flags
df_clean["Reaction_Time_Missing"] = df_clean["Reaction_Time_ms"].isna().astype(int)
df_clean["WorldCupPoints_Missing"] = df_clean["World_Cup_Points_Preseason"].isna().astype(int)

# Then sport-based median imputation for modeling usability
df_clean["Reaction_Time_ms"] = df_clean["Reaction_Time_ms"].fillna(
    df_clean.groupby("Sport")["Reaction_Time_ms"].transform("median")
)

df_clean["World_Cup_Points_Preseason"] = df_clean["World_Cup_Points_Preseason"].fillna(
    df_clean.groupby("Sport")["World_Cup_Points_Preseason"].transform("median")
)

In [26]:
df_clean.isna().sum()

Athlete_ID                       0
Athlete_Name                     0
Country                          0
Gender                           0
Age                              0
Sport                            0
Previous_Olympics                0
Training_Hours_Per_Week          0
Altitude_Training_m              0
Body_Fat_Pct                     0
VO2max                           0
Reaction_Time_ms                64
Career_Injuries                  0
World_Cup_Points_Preseason      67
Country_GDP_per_capita           0
Winter_Sport_Tradition_Index     0
Medal                            0
Reaction_Time_Missing            0
WorldCupPoints_Missing           0
dtype: int64

In [27]:
# Overall fallback medians
df_clean["Reaction_Time_ms"] = df_clean["Reaction_Time_ms"].fillna(
    df_clean["Reaction_Time_ms"].median()
)

df_clean["World_Cup_Points_Preseason"] = df_clean["World_Cup_Points_Preseason"].fillna(
    df_clean["World_Cup_Points_Preseason"].median()
)

In [28]:
df_clean.isna().sum()

Athlete_ID                      0
Athlete_Name                    0
Country                         0
Gender                          0
Age                             0
Sport                           0
Previous_Olympics               0
Training_Hours_Per_Week         0
Altitude_Training_m             0
Body_Fat_Pct                    0
VO2max                          0
Reaction_Time_ms                0
Career_Injuries                 0
World_Cup_Points_Preseason      0
Country_GDP_per_capita          0
Winter_Sport_Tradition_Index    0
Medal                           0
Reaction_Time_Missing           0
WorldCupPoints_Missing          0
dtype: int64

In [29]:
#Feature Engineering
# 1. Binary target for Task 3
df_clean["Medal_Won"] = (df_clean["Medal"] != "None").astype(int)

# 2. Experience + Training composite
df_clean["Experience_Index"] = (
    df_clean["Previous_Olympics"] * df_clean["Training_Hours_Per_Week"]
)

# 3. Physiological efficiency score
df_clean["VO2_BodyFat_Ratio"] = (
    df_clean["VO2max"] / df_clean["Body_Fat_Pct"]
)

# 4. Country support score
df_clean["GDP_Tradition_Score"] = (
    df_clean["Country_GDP_per_capita"] *
    df_clean["Winter_Sport_Tradition_Index"]
)

In [30]:
df_clean.head()

,Athlete_ID,Athlete_Name,Country,Gender,Age,Sport,Previous_Olympics,Training_Hours_Per_Week,Altitude_Training_m,Body_Fat_Pct,VO2max,Reaction_Time_ms,Career_Injuries,World_Cup_Points_Preseason,Country_GDP_per_capita,Winter_Sport_Tradition_Index,Medal,Reaction_Time_Missing,WorldCupPoints_Missing,Medal_Won,Experience_Index,VO2_BodyFat_Ratio,GDP_Tradition_Score
0,MC26_1001,Ben Ogden,USA,M,26.0,Cross-Country,1,35.6,1687.0,8.9,91.5,190.0,1,356.0,80000,0.82,Silver,1,0,1,35.6,10.280899,65600.0
1,MC26_1002,Loic Meillard,SUI,M,30.0,Alpine Skiing,3,22.9,2289.0,13.9,71.4,208.0,1,977.0,93000,0.93,Gold,0,0,1,68.7,5.136691,86490.0
2,MC26_1003,Francesca Lollobrigida,ITA,F,35.0,Speed Skating,1,29.0,394.0,10.1,82.6,189.0,3,416.0,38000,0.82,Gold,0,0,1,29.0,8.178218,31160.0
3,MC26_1004,Maria Nilsson,FRA,F,43.0,Ski Jumping,4,26.2,1239.0,9.1,59.3,183.0,2,801.0,48000,0.87,None,0,0,0,104.8,6.516484,41760.0
4,MC26_1005,Nils Lewis,GER,M,20.0,Short Track,0,20.2,67.0,12.3,63.1,187.0,2,393.0,52000,0.88,None,0,0,0,0.0,5.130081,45760.0

In [31]:
df_clean.shape

(387, 23)

In [32]:
 #Before vs After Cleaning Summary
summary_table = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Total Missing Values",
        "Duplicate Rows Removed",
        "Engineered Features Added"
    ],
    "Before": [
        df.shape[0],
        df.shape[1],
        df.isna().sum().sum(),
        0,
        0
    ],
    "After": [
        df_clean.shape[0],
        df_clean.shape[1],
        df_clean.isna().sum().sum(),
        3,
        6
    ]
})

summary_table

                      Metric  Before  After
0                       Rows     390    387
1                    Columns      17     23
2       Total Missing Values     596      0
3     Duplicate Rows Removed       0      3
4  Engineered Features Added       0      6

In [33]:
#Exporting and saving cleaned data
df_clean.to_csv("milan_cortina_2026_cleaned.csv", index=False)